[project]
name = "movie-recommender-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abdul Sahil", email = "sahiilwork444@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "streamlit>=1.64.0",
]

[project.scripts]
movie-recommender-system = "movie_recommender_system:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
